### ISSUE TITLE
GetInputs: "Don't know about" error when serializing random forest formula

### ISSUE THREAD

**Issue by Corey-Zumar** [duncantl/CodeDepends#21]
Steps to reproduce from an R shell:

```
> model <- randomForest(mpg ~., data = mtcars, keep.forest=TRUE)
> CodeDepends::getInputs(model)
```

The following error is produced:

```
Error in .local(e, collector, basedir, reset, formulaInputs, ...) :
  don't know about randomForest.formularandomForest
```

It may be worth noting that executing the `class()` method on the `model` object produces a 2-element list:

```
> class(model)
[1] "randomForest.formula" "randomForest"
```

**Comment by gmbecker** [comment]
Corey,

You're passing getInputs the actual randomForest object, which it doesn't understand because it only works on things that represent code. What I suspect you wanted to do was:
```
> getInputs(quote(model <- randomForest(mpg ~., data = mtcars, keep.forest=TRUE)))
An object of class "ScriptNodeInfo"
Slot "files":
character(0)

Slot "strings":
character(0)

Slot "libraries":
character(0)

Slot "inputs":
[1] "mtcars"

Slot "outputs":
[1] "model"

Slot "updates":
character(0)

Slot "functions":
randomForest            ~ 
          NA           NA 

Slot "removes":
character(0)

Slot "nsevalVars":
[1] "mpg" "."  

Slot "sideEffects":
character(0)

Slot "code":
model <- randomForest(mpg ~ ., data = mtcars, keep.forest = TRUE)
```

Does that make sense? getInputs needs to be passed the code you want to analyze.

If you are looking to analyze things that are happening in your interactive R session this can be combined with my histry package (just put on CRAN earlier this week) to get a list of top-level expressions that have been run.

**Comment by Corey-Zumar** [comment]
Thanks @gmbecker, that makes sense! I've been using CodeDepends in the context of an interactive R session, but I now realize that this approach isn't always correct because the library is written for static analysis. I'll definitely investigate combining this with "histry" to achieve the intended result.
