### ISSUE TITLE
Error getting the inputs of a body of a function

### ISSUE THREAD

**Issue by wlandau** [duncantl/CodeDepends#27]
From https://github.com/ropensci/drake/issues/335#issuecomment-374933730:

```r
CodeDepends::getInputs(body(graphics::close.screen))
#> Warning: replacing previous import 'graph::addNode' by 'XML::addNode' when
#> loading 'CodeDepends'
#> Warning: replacing previous import 'graph::plot' by 'graphics::plot' when
#> loading 'CodeDepends'
#> Error in validObject(.Object): invalid class "ScriptNodeInfo" object: invalid object for slot "removes" in class "ScriptNodeInfo": got class "list", should be or extend class "character"
```

**Comment by duncantl** [comment]
Thanks. We can add support for the list parameter of rm().

**Comment by gmbecker** [comment]
@wlandau thanks for the report. It doesn't have anything to do with it being a function body, though. The actual problem is the

```
rm(list = <call to paste>, envir = <bla>)
```
pattern within the code body. The problem is that rm handler does not now how to handle that. And it's not clear how it could in a way that is fully correct. 

Note something like `getInputs(install.packages)` does not fail with this error (also note you don't need the body call, we do that for you when given a function).

Now one thing to do that will be safe in this case is to check if the envir argument is set at all (and not to RGlobalEnv), in which case we can ignore the rm call because for now CodeDepends does not track what goes in and out of environments other htan the evaluation environment when the code is evaluated.

More generally this is a tough one...

**Comment by gmbecker** [comment]
@wlandau @duncantl I just checked in something that punts completely if a named argument other than list is present in an `rm()` call and  attempts to handle the case where `list` is specified but is made up of a bunch of strings (in either c() or list(), one assumes) and throws a warning if `list` is specified but dynamically valued.

**Comment by wlandau** [comment]
Thanks, Gabe! dfe31e7384c1137732c04dc277d1ace17d190df8 solves the problem for the purposes of `drake`.
